# Generated by Django 5.1.6 on 2026-03-15 00:31

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('type', models.CharField(choices=[('ADMIN', 'Admin'), ('DRIVER', 'Driver'), ('GUARDIAN', 'Guardian')], db_index=True, max_length=32, verbose_name='User Type')),
                ('profile_image', models.ImageField(blank=True, default='default_images/profile.png', null=True, upload_to='profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'gif'])], verbose_name='Profile Image')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='First Name')),
                ('second_name', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Second Name')),
                ('third_name', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Third Name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Mobile Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20, null=True, verbose_name='Gender')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts', verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff status')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the user has verified their email address.', verbose_name='Verified')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether the user has deleted their account.', verbose_name='Deleted')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverUser',
            fields=[
            ],
            options={
                'verbose_name': 'Driver User',
                'verbose_name_plural': 'Driver Users',
                'permissions': [('can_operate_as_driver', 'Can operate as driver')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='GuardianUser',
            fields=[
            ],
            options={
                'verbose_name': 'Guardian User',
                'verbose_name_plural': 'Guardian Users',
                'permissions': [('can_act_as_guardian', 'Can act as guardian')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
