# Generated by Django 5.1.6 on 2026-04-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantUser',
            fields=[
            ],
            options={
                'verbose_name': 'Assistant User',
                'verbose_name_plural': 'Assistant Users',
                'permissions': [('can_act_as_assistant', 'Can act as assistant')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DRIVER', 'Driver'), ('GUARDIAN', 'Guardian'), ('ASSISTANT', 'Assistant')], db_index=True, max_length=32, verbose_name='User Type'),
        ),
    ]
