# Generated by Django 5.1.6 on 2026-05-05 06:08

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_assistantuser_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondary_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Secondary Mobile Number'),
        ),
    ]
