# Generated by Django 5.1.6 on 2026-05-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_secondary_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pickup_pin',
            field=models.CharField(blank=True, help_text='4-6 digit code for pickup verification (Guardians only).', max_length=6, null=True, verbose_name='Pickup PIN'),
        ),
    ]
