# Generated by Django 5.1.6 on 2026-05-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_pickup_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_pin',
            field=models.CharField(blank=True, help_text='Temporary PIN manually set by admin. Overrides master PIN when present.', max_length=6, null=True, verbose_name='Temporary PIN'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pickup_pin',
            field=models.CharField(blank=True, help_text='4-6 digit master code auto-generated for pickup verification (Guardians only).', max_length=6, null=True, verbose_name='Master Pickup PIN'),
        ),
    ]
