# docker-compose.dev.yml
# Development environment configuration

services:
  # ===================
  # Main Application
  # ===================
  saferoute-backend:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    ports:
      - "127.0.0.1:8001:8000"
    volumes:
      - .:/app
    env_file:
      - ./.envs/.django.env
      - ./.envs/.postgres.env
    depends_on:
      - saferoute-db
      - saferoute-redis

  # ===================
  # Database Services
  # ===================
  saferoute-db:
    image: postgres:17
    env_file:
      - ./.envs/.postgres.env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - saferoute-db-data:/var/lib/postgresql/data

  saferoute-redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    command: [ "redis-server", "--bind", "0.0.0.0" ]
  # ===================
  # Celery Services
  # ===================
  # ===================
  # Development Tools
  # ===================
  # taheed-pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "127.0.0.1:8888:80"
  #   env_file:
  #     - ./.envs/.postgres.env
  #   volumes:
  #     - taheed-pgadmin-data:/var/lib/pgadmin

volumes:
  saferoute-db-data:
