# Generated by Django 5.1.6 on 2026-04-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='pickup_pin',
            field=models.CharField(blank=True, help_text='4-6 digit code for pickup verification.', max_length=6, null=True, verbose_name='Pickup PIN'),
        ),
        migrations.AlterField(
            model_name='child',
            name='grade',
            field=models.CharField(blank=True, choices=[('KG1', 'KG 1'), ('KG2', 'KG 2'), ('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6'), ('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8'), ('GRADE_9', 'Grade 9'), ('GRADE_10', 'Grade 10'), ('GRADE_11', 'Grade 11'), ('GRADE_12', 'Grade 12')], max_length=20, null=True, verbose_name='Grade'),
        ),
    ]
