# Generated by Django 5.1.6 on 2026-04-21 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_child_pickup_pin_alter_child_grade'),
        ('users', '0003_assistantuser_alter_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="e.g. Grandma's House", max_length=255, verbose_name='Description')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
                ('gmaps_url', models.URLField(blank=True, null=True, verbose_name='Google Maps URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to='users.guardianuser', verbose_name='Guardian')),
            ],
            options={
                'verbose_name': 'Student Saved Location',
                'verbose_name_plural': 'Student Saved Locations',
            },
        ),
        migrations.CreateModel(
            name='LocationChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(verbose_name='Target Date')),
                ('change_type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Drop-off'), ('both', 'Both')], default='both', max_length=20, verbose_name='Change Type')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending_review', max_length=30, verbose_name='Status')),
                ('effective_until', models.DateTimeField(blank=True, help_text='When the lock on new requests for this scope/date clears.', null=True, verbose_name='Effective Until')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_change_requests', to='users.guardianuser', verbose_name='Guardian')),
                ('students', models.ManyToManyField(related_name='location_change_requests', to='children.child', verbose_name='Students')),
                ('new_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='children.studentsavedlocation', verbose_name='New Location')),
            ],
            options={
                'verbose_name': 'Location Change Request',
                'verbose_name_plural': 'Location Change Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
