# Generated by Django 5.1.6 on 2026-05-05 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_studentsavedlocation_locationchangerequest'),
        ('users', '0004_user_secondary_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='users.guardianuser', verbose_name='Guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_messages', to='children.child', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Guardian Message',
                'verbose_name_plural': 'Guardian Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='children.child', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Absence',
                'verbose_name_plural': 'Student Absences',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
