# Generated by Django 5.1.6 on 2026-05-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_guardianmessage_studentabsence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='pickup_pin',
        ),
    ]
