# Generated by Django 5.1.6 on 2026-04-14 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('users', '0002_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Plate Number')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bus Model')),
                ('capacity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Capacity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='users.driveruser', verbose_name='Driver')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Route Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('school_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='School Name')),
                ('school_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='School Latitude')),
                ('school_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='School Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='trips.bus', verbose_name='Assigned Bus')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Stop Name')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('expected_pickup_time', models.TimeField(blank=True, null=True, verbose_name='Expected Pickup Time')),
                ('expected_dropoff_time', models.TimeField(blank=True, null=True, verbose_name='Expected Drop-off Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.route', verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Route Stop',
                'verbose_name_plural': 'Route Stops',
                'ordering': ['route', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('PICKUP', 'Pickup (To School)'), ('DROPOFF', 'Drop-off (From School)')], default='PICKUP', max_length=20, verbose_name='Trip Type')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual End Time')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Current Latitude')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Current Longitude')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.bus', verbose_name='Bus')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='users.driveruser', verbose_name='Driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.route', verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_days', models.JSONField(default=list, help_text='Days of week this child is subscribed for this route (e.g. ["SUNDAY","MONDAY"])', verbose_name='Subscription Days')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='children.child', verbose_name='Child')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_children', to='trips.route', verbose_name='Route')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_children', to='trips.routestop', verbose_name='Pickup/Dropoff Stop')),
            ],
            options={
                'verbose_name': 'Route Child',
                'verbose_name_plural': 'Route Children',
                'unique_together': {('route', 'child')},
            },
        ),
        migrations.CreateModel(
            name='TripChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('PICKED_UP', 'Picked Up'), ('DROPPED_OFF', 'Dropped Off'), ('ABSENT', 'Absent')], default='WAITING', max_length=20, verbose_name='Status')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Picked Up At')),
                ('dropped_off_at', models.DateTimeField(blank=True, null=True, verbose_name='Dropped Off At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_records', to='children.child', verbose_name='Child')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_children', to='trips.routestop', verbose_name='Stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_children', to='trips.trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'Trip Child Record',
                'verbose_name_plural': 'Trip Children Records',
                'unique_together': {('trip', 'child')},
            },
        ),
    ]
