# Generated by Django 5.1.6 on 2026-04-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20, verbose_name='Bus Status'),
        ),
        migrations.AlterField(
            model_name='routechild',
            name='subscription_days',
            field=models.JSONField(default=list, help_text='Days of week this child is subscribed (e.g. ["SUNDAY","MONDAY"])', verbose_name='Subscription Days'),
        ),
    ]
