# Generated by Django 5.1.6 on 2026-04-21 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_bus_status_alter_routechild_subscription_days'),
        ('users', '0003_assistantuser_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_trips', related_query_name='assisted_trip', to='users.assistantuser', verbose_name='Assistant'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_trips', related_query_name='driven_trip', to='users.driveruser', verbose_name='Driver'),
        ),
    ]
