# Generated by Django 5.1.6 on 2026-05-15 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_school'),
        ('users', '0004_user_secondary_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to='users.assistantuser', verbose_name='Assigned Assistant'),
        ),
    ]
