# Generated by Django 5.1.6 on 2026-04-14 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRIP_STARTED', 'Trip Started'), ('TRIP_COMPLETED', 'Trip Completed'), ('TRIP_CANCELLED', 'Trip Cancelled'), ('CHILD_PICKED_UP', 'Child Picked Up'), ('CHILD_DROPPED_OFF', 'Child Dropped Off'), ('CHILD_ABSENT', 'Child Marked Absent'), ('BUS_APPROACHING', 'Bus Approaching Your Stop'), ('BUS_DELAYED', 'Bus Delayed'), ('GENERAL', 'General'), ('SYSTEM', 'System'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired')], max_length=50, unique=True, verbose_name='Notification Type')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Arabic)')),
                ('body_en', models.TextField(verbose_name='Body (English)')),
                ('body_ar', models.TextField(blank=True, null=True, verbose_name='Body (Arabic)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('type', models.CharField(choices=[('TRIP_STARTED', 'Trip Started'), ('TRIP_COMPLETED', 'Trip Completed'), ('TRIP_CANCELLED', 'Trip Cancelled'), ('CHILD_PICKED_UP', 'Child Picked Up'), ('CHILD_DROPPED_OFF', 'Child Dropped Off'), ('CHILD_ABSENT', 'Child Marked Absent'), ('BUS_APPROACHING', 'Bus Approaching Your Stop'), ('BUS_DELAYED', 'Bus Delayed'), ('GENERAL', 'General'), ('SYSTEM', 'System'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired')], default='GENERAL', max_length=50, verbose_name='Notification Type')),
                ('target_all', models.BooleanField(default=True, verbose_name='Send to All Users')),
                ('target_guardians', models.BooleanField(default=False, verbose_name='Send to Guardians')),
                ('target_drivers', models.BooleanField(default=False, verbose_name='Send to Drivers')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='Sent By')),
            ],
            options={
                'verbose_name': 'Broadcast Notification',
                'verbose_name_plural': 'Broadcast Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True, verbose_name='Device Token')),
                ('device_type', models.CharField(blank=True, choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], max_length=20, null=True, verbose_name='Device Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRIP_STARTED', 'Trip Started'), ('TRIP_COMPLETED', 'Trip Completed'), ('TRIP_CANCELLED', 'Trip Cancelled'), ('CHILD_PICKED_UP', 'Child Picked Up'), ('CHILD_DROPPED_OFF', 'Child Dropped Off'), ('CHILD_ABSENT', 'Child Marked Absent'), ('BUS_APPROACHING', 'Bus Approaching Your Stop'), ('BUS_DELAYED', 'Bus Delayed'), ('GENERAL', 'General'), ('SYSTEM', 'System'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired')], default='GENERAL', max_length=50, verbose_name='Notification Type')),
                ('channel', models.CharField(choices=[('PUSH', 'Push Notification'), ('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('SMS', 'SMS')], default='IN_APP', max_length=20, verbose_name='Channel')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=20, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional JSON payload (e.g. trip_id, child_id, etc.)', verbose_name='Extra Data')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('error_message', models.TextField(blank=True, help_text='Populated if sending failed', null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='children.child', verbose_name='Related Child')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
