# Generated by Django 5.1.6 on 2026-05-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='target_assistants',
            field=models.BooleanField(default=False, verbose_name='Send to Assistants'),
        ),
    ]
